### ISSUE TITLE
[DATA REQUEST] Add ACCESS-OM2 runs using ERA5

### ISSUE THREAD

**Issue by anton-seaice** [ACCESS-NRI/access-nri-intake-catalog#127]
# Description of the data product

ACCESS-OM2 Runs using ERA5 as a data atmosphere to force the model instead of JRA55

There are 8 runs - for each combination of IAF/RYF, ERA5/JRA55, 0.25/1 deg

# Location of the data product on Gadi

Data location in /g/data/ik11/outputs/ (see https://forum.access-hive.org.au/t/era-5-forced-access-om2-simulations/1103)

# Checklist

Add a "x" between the brackets to all that apply
- [x] This data product is stable (unlikely to change substantially or move)
- [x] This data product is of use to the broader community
- [x] This data product is documented: (see links in https://forum.access-hive.org.au/t/era-5-forced-access-om2-simulations/1103)
- [x] This data product is licensed under 'Acknoledge COSIMA'
- [x] Those who want to access this data can be added to the project that houses it

**Comment by anton-seaice** [comment]
@aekiss @rmholmes - Do you think the ERA5 runs of OM2 are appropriate for adding to the intake catalog?

**Comment by rmholmes** [comment]
Thanks for putting this together.

In terms of whether these runs are appropriate for inclusion in the intake catalog. As far as my understanding of the intake catalog (something like an updated, much better, version of the COSIMA cookbook database system), I think I would say overall yes, noting that there are still some outstanding issues (see @aekiss's list https://github.com/COSIMA/access-om2/issues/242#issuecomment-1487906161). However, given the push toward MOM6 and ACCESS-OM3, at the moment I don't think I see this situation changing rapidly, and so the "is this data product stable" question is probably "yes".

With regards to "is this data product licensed under `Acknowledge COSIMA`" -> I'm not sure, it should be. What do I have to do for this? Is it enough to have the "Conditions of use" section under "notes" in the `metadata.yaml` files as @dougiesquire has added?

**Comment by anton-seaice** [comment]
Thanks @rmholmes !

> With regards to "is this data product licensed under Acknowledge COSIMA" -> I'm not sure, it should be. What do I have to do for this? Is it enough to have the "Conditions of use" section under "notes" in the `metadata.yaml` files as @dougiesquire has added?
What @dougiesquire added is consistent with other OM2 runs, so in that way its enough :)

**Comment by anton-seaice** [comment]
There is a minor extension these datasets:

https://forum.access-hive.org.au/t/era-5-forced-access-om2-simulations/1103/6?u=anton

**Comment by dougiesquire** [comment]
Thanks @anton-seaice. These should be picked up automatically the next time the catalog is built.

**Comment by anton-seaice** [comment]
Just leaving a note from Ryans post:

_For anyone who is using recent data from the access-om2-025/025deg_era5_iaf run, ... Note that 2023 is now output043 and run as one contiguous year, replacing the previous output043-045 which were irregular runs of just a few months._

Meaning you might get errors like this:

`No such file or directory: '/g/data/ik11/outputs/access-om2-025/025deg_era5_iaf/output045/ocean/ocean-2d-surface_pot_temp-1-monthly-mean-ym_2023_05.nc'` where it tries to access data that doesn't exist anymore

But as i understand it that will be fixed in the next-rebuild without any intervention
