### ISSUE TITLE
ACCESS-OM3 Builder

### ISSUE THREAD

**Issue by anton-seaice** [ACCESS-NRI/access-nri-intake-catalog#151]
# Is your feature request related to a problem? Please describe.

To support quick analysis of new runs in access-om3, we will need a access-om3 builder. 

# Describe the feature you'd like

We want to be able to build a temporary / adhoc datastore from a single run of access-om3 output for quick analysis against big picture metrics (e.g. similar to the figures in access-om2 paper)

# Describe alternatives you've considered

We could use file paths until access-om3 is further developed

# Additional context

At some point we might automate building the datastore into payu.

**Comment by anton-seaice** [comment]
I guess we need something similar to:

https://github.com/ACCESS-NRI/access-nri-intake-catalog/blob/c80df8701a82e65e4ed7800b7e71c9c02cb27c62/src/access_nri_intake/source/builders.py#L187

but for access-om3 output.

I don't think we need metadata.yaml files yet for the experiments ? But we will need to add them at some point

**Comment by dougiesquire** [comment]
Thanks for opening @anton-seaice. This should be straightforward
