### ISSUE TITLE
Should we add a "wave" realm?

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/access-nri-intake-catalog#155]
With the addition of the [ACCESS-OM3 builder](#152), which can include WW3 data, it may be nice to add a "wave" realm to the [schema](https://github.com/ACCESS-NRI/schema/blob/main/experiment_asset.json). Currently the ACCESS-OM3 builder assigns wave data to the "ocean" realm, but having a "wave" realm will make it more findable. Adding a "wave" realm means deviating even farther from the [CMIP6 "realm" controlled vocab](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/main/CMIP6_realm.json), which we currently follow with the addition of `"none"` and `"unknown"`.

**Comment by aidanheerdegen** [comment]
> Adding a "wave" realm means deviating even farther from the [CMIP6 "realm" controlled vocab](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/main/CMIP6_realm.json), which we currently follow with the addition of `"none"` and `"unknown"`.

Is it worth making an issue to get a wave realm added to the WCRP controlled vocabs?

**Comment by dougiesquire** [comment]
> Is it worth making an issue to get a wave realm added to the WCRP controlled vocabs?

Somehow I don't think that would be an easy or quick process...

**Comment by aidanheerdegen** [comment]
> Somehow I don't think that would be an easy or quick process

Be the change you wish to see in the world

**Comment by dougiesquire** [comment]
Closed by #161 and #162
