### ISSUE TITLE
Add additional CMS and NCI intake catalogs

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/access-nri-intake-catalog#16]
CLEX CMS manages a conventional [Intake catalog of Intake-ESM datastores](https://github.com/coecms/nci-intake-catalogue) on NCI. We could include these as entries in the ACCESS-NRI catalog. Potential candidates are (tick when added):

- [ ] `era5-land` @ `/g/data/hh5/public/apps/nci-intake-catalogue/era5-land`
- [ ] `era5` @ `/g/data/hh5/public/apps/nci-intake-catalogue/era5`
- [ ] `erai` @ `/g/data/hh5/public/apps/nci-intake-catalogue/erai`
- [ ] `cmip5` @ `/g/data/hh5/public/apps/nci-intake-catalogue/esgf/cmip5`
- [ ] `cmip6` @ `/g/data/hh5/public/apps/nci-intake-catalogue/esgf/cmip6`
- [ ] `cordex` @ `/g/data/hh5/public/apps/nci-intake-catalogue/esgf/cordex`

NCI also manage Intake-ESM datastores for their CMIP collections they we should add:

- [x] `cmip5-al33` @ `/g/data/dk92/catalog/v2/esm/cmip5-al33`
- [x] `cmip5-rr3` @ `/g/data/dk92/catalog/v2/esm/cmip5-rr3`
- [x] `cmip6-fs38` @ `/g/data/dk92/catalog/v2/esm/cmip6-fs38`
- [x] `cmip6-oi10` @ `/g/data/dk92/catalog/v2/esm/cmip6-oi10`
- [ ] `era5-rt52` @ `/g/data/dk92/catalog/v2/esm/era5-rt52`

There's obviously some overlap between the two sets of datastores. To avoid confusion, we should avoid duplication in what we add to the ACCESS-NRI catalog.

**Comment by dougiesquire** [comment]
Note a config file and Translator exist already for adding the CLEX CMS `erai` Intake-ESM datastore, but this datastore is currently broken:

<img width="698" alt="Screenshot 2023-06-18 at 9 36 29 pm" src="https://github.com/ACCESS-NRI/access-nri-intake-catalog/assets/42455466/3eb1019a-f743-4b00-bffb-7d15b7a510ff">

There's a ticket in to CMS help about this.

**Comment by rbeucher** [comment]
With the conclusion of CLEX and the decommissioning of hh5, I believe it no longer makes sense to add the intake-esm datastores from hh5. Instead, I suggest we focus on integrating the NCI intake-ESM datastores, which will be more relevant for ongoing and future projects.

In particular, the era-rt52 collection is definitely a good candidate for inclusion in the ACCESS catalog

I'll be closing this issue and will open a new one specifically for tracking the integration of era-rt52 into the ACCESS-nri-intake-catalog
