### ISSUE TITLE
Update metadata schema

### ISSUE THREAD

**Issue by jo-basevi** [ACCESS-NRI/access-nri-intake-catalog#164]
The `experiment-metadata` schema has been updated to version `1-0-3`: https://github.com/ACCESS-NRI/schema/pull/19, where the only change is that the `nominal_resolution` has been expanded to accept strings and arrays types (previously just arrays). 

Just creating an issue incase this impacts the schema validation checks in the catalogue.

**Comment by marc-white** [comment]
I'm flagging this one to myself as a reminder to check what's happened with this
