### ISSUE TITLE
update intake-dataframe-catalog version in ci/environment-3.11.yml

### ISSUE THREAD

**Issue by paolap** [ACCESS-NRI/access-nri-intake-catalog#177]
In the ci/environment-3.11.yml file which is the suggested conda env for pull-request, update
	intake-dataframe-catalog>=0.2.3
to
       intake-dataframe-catalog>=0.2.4
To avoid installing 0.2.3 that seems to create issues with the catalog manager code

**Comment by dougiesquire** [comment]
Thanks @paolap. My guess is that you somehow ended up with `intake>=2.0.0`. I'm not sure how this happened since `intake=0.7.0` is pinned here. Regardless, there's no harm in explicitly specifying `intake-dataframe-catalog>=0.2.4` as you suggest.

**Comment by paolap** [comment]
Yep that was my guess too, that's why I thought it might be the previous version of the dataframe, I thought you pinned intake in 2.4 but not in 2.3? I might have been confused

**Comment by dougiesquire** [comment]
> I thought you pinned intake in 2.4 but not in 2.3

Yeah, but it should be pinned in recent versions of `access-nri-intake-catalog` as well. Regardless, I changed to `intake-dataframe-catalog>=0.2.4` now - thanks for opening!
