### ISSUE TITLE
Ship schema with package

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/access-nri-intake-catalog#185]
Current behaviour is that the schema used to validate the datastore and catalog entries [are downloaded and cached](https://access-nri-intake-catalog.readthedocs.io/en/latest/management/schema.html) the first time `access-nri-intake` is imported - see [here](https://github.com/ACCESS-NRI/access-nri-intake-catalog/blob/a07470a7b94ceecc62b98f9f11ac30c11a5c3344/src/access_nri_intake/source/__init__.py#L20-L25) and [here](https://github.com/ACCESS-NRI/access-nri-intake-catalog/blob/a07470a7b94ceecc62b98f9f11ac30c11a5c3344/src/access_nri_intake/catalog/__init__.py#L21-L26). This has obvious issues when someone is trying to use `access-nri-intake` for the first time from a computer without network access (e.g. Gadi compute nodes).

To avoid this issue, we probably need to refactor how the schema are handled so that the appropriate schema are shipped with the `access-nri-intake` package.

**Comment by dougiesquire** [comment]
@marc-white is this something you could take on?

**Comment by aidanheerdegen** [comment]
Surely we can ship a datafile with a conda package?

**Comment by dougiesquire** [comment]
Yeah, we can. It just requires a small amount of thought/refactor so that we can easily update the schema

**Comment by marc-white** [comment]
Dumping here for my own reference: https://sixty-north.com/blog/including-package-data-in-python-packages.html
