### ISSUE TITLE
`get_timeinfo` could be more robust

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/access-nri-intake-catalog#20]
The code for getting the frequency, start date and end date of the variables in a file was stolen and adapted very slightly from the [cosima cookbook](https://github.com/COSIMA/cosima-cookbook/blob/master/cosima_cookbook/database.py#L565). It works okay, but it could probably be more robust. 

As a example, there're data in some of the COSIMA experiments (e.g. some of the files for the `wdet100` variable in `01deg_jra55v13_ryf9091`) that comprise a single timestep and do not include `time_bounds`. These get flagged as fixed frequency `fx` even though they are actually `1mon`. In this case, I think this is actually more of a data issue - I don't know of any way to get the frequency in this case without trying to parse it from the (non-standardised) filename (which I don't think we want to do).

**Comment by dougiesquire** [comment]
Note since #91, the filename is also parsed for frequency information. If the frequency determined from the filename and file contents differ, a warning is thrown and:

- if the contents frequency is `fx`, the filename frequency is used
- otherwise the contents frequency is used

**Comment by rbeucher** [comment]
Looks like a data issue for me. If you can't extract the information from the file .. 

I think a warning is good. 

Closing this but feel free to reopen.
