### ISSUE TITLE
Handling of static variables.

### ISSUE THREAD

**Issue by AndyHoggANU** [ACCESS-NRI/access-nri-intake-catalog#217]
# Is your feature request related to a problem? Please describe.

Many of our models write out static information (e.g. grid information) with every segment of the run. This confuses the intake catalogue. For example, if we do this:

```
import intake
catalog = intake.cat.access_nri
experiment='1deg_jra55_iaf_omip2_cycle1'
cat_subset = catalog.search(name = experiment)
dxt = cat_subset[experiment].search(variable = 'dxt',frequency = 'fx').to_dask()['dxt']
```
then we get an error -- because there are many static files which meet the criteria, but they can't be stitched together. The suggestion on the intake tutorial is to use:

```
dxt = cat_subset[experiment].search(variable = 'dxt',frequency = 'fx',path=".*output000.*").to_dask()['dxt']
```

which is fine when you know something about the path name. But we would quite like the user to be oblivious to file names. For example, if we do this:

```
experiment='1deg_jra55_iaf_omip2_cycle2'
cat_subset = catalog.search(name = experiment)
dxt = cat_subset[experiment].search(variable = 'dxt',frequency = 'fx',path=".*output000.*").to_dask()['dxt']
```
then we also get a failure ...

# Describe the feature you'd like

For `fx` variables, maybe we could make intake read only one file in?

# Describe alternatives you've considered

Sorry, no other real ideas....

**Comment by marc-white** [comment]
I think this dovetails very nicely with what @charles-turner-1 is looking at on #212 , which will hopefully lead us to returning something sensible when you make a query like your first one @AndyHoggANU .

**Comment by charles-turner-1** [comment]
Yup, the work in #212 should address this issue.

**Comment by AndyHoggANU** [comment]
OK, great. Feel free to close this one if you want to tidy up?
