### ISSUE TITLE
Ensure we can upload to pypi

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/access-nri-intake-catalog#227]
Hi @dougiesquire 

When you have a chance, can you add access-nri as owner on pypi?

Thank you

**Comment by dougiesquire** [comment]
I've just made the access-nri PyPI account an owner of both `access-nri-intake` and `intake-dataframe-catalog`

**Comment by rbeucher** [comment]
Thanks. Sorry for the bother 🙏
