### ISSUE TITLE
Configuration: CLI utility & TUI config tool

### ISSUE THREAD

**Issue by charles-turner-1** [ACCESS-NRI/access-nri-intake-catalog#235]
# Is your feature request related to a problem? Please describe.

Following the discussion in #191, it looks like it would be useful to add a CLI/TUI tool to create & pre-populate a configuration that allows the user to select different catalog versions, as well as (potentially) some additional configuration.

# Describe the feature you'd like

A console script that creates a pre-populated configuration file, as well as the ability to enter a TUI which walks the user through configuration if desired.

# Describe alternatives you've considered

See discussion in #191.

# Additional context

- I plan on using [textual](https://textual.textualize.io/) to build the TUI.
- I'm going to keep this completely separate for #191 for the time being, & just build a generic tool skeleton - we can then fit it to the configuation.

**Comment by rbeucher** [comment]
Not sure about the TUI. I think we should keep it simple for now.
