### ISSUE TITLE
[Potential BUG] Teardown of temporary file structures in tests may not be complete

### ISSUE THREAD

**Issue by charles-turner-1** [ACCESS-NRI/access-nri-intake-catalog#270]
# Describe the bug

There are some tests in `tests/test_cli.py` which use temporary directories: eg [link](https://github.com/ACCESS-NRI/access-nri-intake-catalog/blob/2fdc8cca661671d9eb9b621bfc021da61299f51f/tests/test_cli.py#L235). 

The tempfile module can be a bit finnicky when not using a context manager & I think there's the possibility that we're not cleaning up out temporary directories in an ideal fashion.

PR #266 (end to end build test) uses pytest's built in fixtures to handle the temporary filesystem stuff, and I think it would be ideal to move to using this as soon as we can.

# Additional context

Noted during #268 .

**Comment by marc-white** [comment]
Repeating my comment form #268 : several of the `test_cli` tests need access to multiple tempdirs during the same test, so we need a way of supporting that (without creating several differently-named-but-identically-functioning fixtures).

**Comment by marc-white** [comment]
@charles-turner-1 what was your plan for removing the `mocks` in the test suite? I think that's probably interrelated with this issue.

**Comment by charles-turner-1** [comment]
Yeah - just merged #268 so provided the workflow trigger is running correctly from main, I'll start looking into this. Can we just use subdirectories within the pytest provided temporary directory?

I think there are a few general test cleanup things we might want to do, so maybe it's worth creating a meta-issue regarding test cleanup/optimisation & then we can start ticking items off that?

**Comment by charles-turner-1** [comment]
I'm gonna start looking into this soon, so I might have to ask you about how the separate tempdirs work tomorrow.

Not sure if you know about [this tool](https://github.com/asottile/detect-test-pollution) but might be relevant/useful (partially linking for my own benefit before I forget it exists).

**Comment by marc-white** [comment]
@charles-turner-1 I've stripped out the `tempfile` usage and replaced it with fixtures, so it's good to go if you want to use this branch to make some mock changes. Otherwise, I can just create a PR for this change only.

**Comment by charles-turner-1** [comment]
I think let's keep them separate - I'm trying to juggle a few things right now and not making much progress with any of them so if you request a review off me I'll be able to do it ASAP.
