### ISSUE TITLE
Add metadata validation tests

### ISSUE THREAD

**Issue by marc-white** [ACCESS-NRI/access-nri-intake-catalog#285]
# Is your feature request related to a problem? Please describe.

Following on from #283 , a good sanity-check test would be to run the `metadata-validate` tool over all the reference `metadata.yaml` stored in the reference directory (`config/metadata_sources`). Not only would this prevent bad metadata leaking into the repo, it would also provide a test whenever the metadata schema is updated.

# Describe the feature you'd like

Add a test suite that runs `metadata-validate` over all `metadata.yaml` in the `config/metadata_sources` directory.

# Describe alternatives you've considered

I thought about requesting this as a CI check instead, but I realized it's faster & easier to do at the `pytest` level.

# Additional context

Nil.

**Comment by marc-white** [comment]
I've added this ability in the 285 branch, including the ability to automatically find and test existing `catalog_sources`. Now blocked by the metadata errors in #286 .

**Comment by charles-turner-1** [comment]
Just merged #286 into main, and main into branch 285 - I think it's ready to merge.

**Comment by charles-turner-1** [comment]
Closed by #288.
