### ISSUE TITLE
[BUG] Metadata issues in v1.0.0b2

### ISSUE THREAD

**Issue by marc-white** [ACCESS-NRI/access-nri-intake-catalog#286]
# Describe the bug

There are other metadata issues in the v1.0.0b2 release that need fixing. This is a catch-all ticket for tracking them.

# To Reproduce

Attempt a catalog build using v1.0.0b2.

**Comment by marc-white** [comment]
Of the `metadata.yaml` stored in `config/metadata_sources`, the following fail validation:

`era5-rt52`
-----------

```
Validating config/metadata_sources/era5-rt52/metadata.yaml... 

VALIDATION FAILED:

01 | reference : ['https://rmets.onlinelibrary.wiley.com/doi/10.1002/qj.3803', 'https://rmets.onlinelibrary.wiley.com/doi/10.1002/qj.4174', 'https://www.ecmwf.int/en/elibrary/81149-global-stratospheric-temperature-bias-and-other-stratospheric-aspects-era5-and', 'https://www.ecmwf.int/en/elibrary/19911-low-frequency-variability-and-trends-surface-air-temperature-and-humidity-era5-and', 'https://www.ecmwf.int/en/publications/search?searc_all_field=era5'] is not of type 'string', 'null'
02 | related_experiments : None is not of type 'array'
03 | keywords : None is not of type 'array'
```

`narclim2-zz63`
----------------

The `metadata-validate` script fails completely, due to the mixing of 'long string' and 'array' types in the `reference` field. Once that is cleared:

```
Validating config/metadata_sources/narclim2-zz63/metadata.yaml... 

VALIDATION FAILED:

01 | frequency : 'mon' is not valid under any of the given schemas
02 | frequency : 'day' is not valid under any of the given schemas
03 | reference : ['https://doi.org/10.1029/2021EF002625', 'https://doi.org/10.5194/gmd-2024-41', 'https://doi.org/10.5194/gmd-2024-87'] is not of type 'string', 'null'
04 | related_experiments : None is not of type 'array'
```

I will fix `era5` on this branch, and @charles-turner-1 can transfer it into the live location on `xp65`. I understand he has already made a fix to `narclim2` on the live, so I will cross-deck the changes from there.

**Comment by charles-turner-1** [comment]
Have already fixed this in `/g/data/xp65/admin/intake/metadata/rcm_ccam_hq89`

```bash
$ cd /g/data/xp65/admin/intake/metadata/rcm_ccam_hq89
$ metadata-validate metadata.yaml
$ Validating metadata.yaml...

VALIDATION FAILED:

01 | frequency : 'day' is not valid under any of the given schemas
02 | frequency : 'mon' is not valid under any of the given schemas
```

**Comment by charles-turner-1** [comment]
Turned out to already have been corrected in the package `config/metadata_sources/rcm-ccam-hq89/metadata.yaml`
