### ISSUE TITLE
Enhanced translator error messages.

### ISSUE THREAD

**Issue by charles-turner-1** [ACCESS-NRI/access-nri-intake-catalog#297]
# Is your feature request related to a problem? Please describe.

#279 and #290 : when builds fail due to translator errors, it can be difficult to reliably identify which translator failed. This can be an issue at catalog build time if NCI datastores change.

# Describe the feature you'd like

Translators to provide a class name when failing such that debugging translator failures is more straightforward.

# Describe alternatives you've considered

<Replace this text with a clear and concise description of any alternative solutions or features you've considered.>

# Additional context

<Replace this text with any other relevant information about your suggestion>

**Comment by charles-turner-1** [comment]
@marc-white I'm wrapping up the translator errors now - PR should be in ASAP.

**Comment by marc-white** [comment]
Once that's in, for speed I won't bother with a new draft release - I'll just do a local install of the updated `main` and run a build from that.

**Comment by marc-white** [comment]
@charles-turner-1 how are you traveling? Can I help at all?

**Comment by charles-turner-1** [comment]
See #298 - got hung up trying to move all the error handling into a single decorator - struggling to get it to grab func.__name__ correctly.

**Comment by charles-turner-1** [comment]
Closed by #298.
