### ISSUE TITLE
Notifying user if they are not connected to correct project for data retrieval

### ISSUE THREAD

**Issue by headmetal** [ACCESS-NRI/access-nri-intake-catalog#48]
**Feature request**

Problem: If user has not included the data source project in the 'Storage' field when starting the notebook, of course they cannot load data from that source (example error attached). Can we possibly use the `job_script_options.json` (example attached) file to flag this before trying to load the data? 

Obviously we can't check if a user is a member of a given project, but a missing project storage location might give us a hint.

Error:
<img width="2283" alt="Screenshot 2023-04-27 at 13 13 24" src="https://user-images.githubusercontent.com/5642928/234754207-4255aa58-d61e-49c9-ad81-9d882448ef1f.png">

job_script_options.json
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/5642928/234754339-e0527057-7cd2-4add-9e9d-bfca3f40edb8.png">

**Comment by dougiesquire** [comment]
Nice idea, but it's specific to the ARE (not saying we shouldn't do it, just flagging that it won't cover all use cases)
