### ISSUE TITLE
ipywidgets fastprogress warning when using search().to_subcatalogue()

### ISSUE THREAD

**Issue by headmetal** [ACCESS-NRI/access-nri-intake-catalog#49]
Are we maybe missing a module in the nri-cat conda env?

<img width="1517" alt="image" src="https://user-images.githubusercontent.com/5642928/234754990-5f2c72a9-ae66-4b75-ae4e-fc0a2b7f6aa6.png">

**Comment by dougiesquire** [comment]
This is a [known issue](https://github.com/fastai/fastprogress/issues/91) that will hopefully be fixed soon. Not sure there's much we can do at this point unfortunately

**Comment by dougiesquire** [comment]
Closing as updating `ipywidgets` should fix the problem. Please feel free to reopen
