### ISSUE TITLE
matplotlib not included in nri-cat conda env

### ISSUE THREAD

**Issue by headmetal** [ACCESS-NRI/access-nri-intake-catalog#50]
Obviously this isn't _needed_ for intake to work, but is needed to work through the provided example in `example_usage.ipynb`

<img width="612" alt="image" src="https://user-images.githubusercontent.com/5642928/234755755-550c41f9-c0ea-4201-bf3b-8fc7950a87d7.png">

**Comment by dougiesquire** [comment]
Closing as we're now recommending users use the `xp65` environment, which includes `matplotlib`. Those wanting to manage their own envs will need to make sure `matplotlib` is installed to run the tutorials.
