### ISSUE TITLE
Ideas for "first-time user" pointers

### ISSUE THREAD

**Issue by svenbuder** [ACCESS-NRI/access-nri-intake-catalog#76]
Because I have not worked on Gadi before, I was the perfect "new PhD student" test-case and had to take some additional steps to make things work.

We can possibly add them to a "If you have not setup conda on Gadi before, this might be helpful" - Section:

1) Adjust your default project upon login (if you are part of more than 1 project)
$ vi $HOME/.config/gadi-login.conf
(I had to change mine to tm70, because I accidentally installed into the wrong project directory)

2) If you have not used conda before, initialise your conda
$ conda init bash

3) Adjust the commands that are run for conda upon login (note: they will disable automatic environment activations, so that you can activate one of your choice)
$ vi ~/.condarc
>>>
auto_activate_base: false
envs_dirs:
  - /scratch/$PROJECT/$USER/conda/envs
  - /g/data/hh5/public/apps/miniconda3/envs
pkgs_dirs:
  - /scratch/$PROJECT/$USER/conda/pkgs
conda-build:
  root-dir: /scratch/$PROJECT/$USER/conda/bld
<<<

Once I had done that, I could run your commands without error 
$ module use /g/data/hh5/public/modules
$ module load conda/analysis3
$ conda deactivate
$ conda create -n access-nri-catalog -y -c conda-forge -c accessnri jupyterlab dask-labextension matplotlib access-nri-intake

**Comment by svenbuder** [comment]
For the ARE setup, I would add a first warning that you have to load the storage for the catalogs you may want to read in.
So maybe just add a one liner:
To run through the default tutorial (incl. the loading of "ocean_scalar.*" files from project ik11), you would need access to
storage "gdata/tm70+gdata/hh5/+gdata/ik11"

And maybe just add link to "Get started with JupyterLab on NCI": https://opus.nci.org.au/display/OOD/3.1+Starting+JupyterLab+App

**Comment by dougiesquire** [comment]
Thanks @svenbuder. I'm incorporated this feedback into an overhaul of the docs (#81) that will be merged soon, so I'm closing this issue. Please feel free to add anything else that comes to mind.
